run:
  issues:
    exclude-rules:
      - linters: [stylecheck]
        text: "ST1005:"
    exclude-dirs:
      - .tmp
      - vendor
linters:
  disable-all: true
  enable:
    # - errcheck
    - asciicheck
    - copyloopvar
    - goconst
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - sqlclosecheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace
linters-settings:
  gofumpt:
    extra-rules: true
  misspell:
    locale: US  
